spring:
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    admin:
      # By default, if the broker is not available, a message will be logged, but the context will continue to load.
      # You can programmatically invoke the admin’s initialize() method to try again later.
      # If you wish this condition to be considered fatal, set the admin’s fatalIfBrokerNotAvailable property to
      # true and the context will fail to initialize.
      fail-fast: true
