server:
  port: 8081

management:
  metrics:
    export:
      elastic:
        host: http://localhost:9200

        index: microservices-metrics
        # No rollover indices. That's why explicitly don't specify a `index-date-format` here!
        index-date-format:

  endpoints:
    web:
      exposure:
        include: "*"

spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      properties:
        spring.json.trusted.packages: "*"
      group-id: foo
      auto-offset-reset: earliest
      client-id: spring-kafka-consumer-hello-world-app
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
